apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memo-prd-backend
  namespace: argocd
spec:
  destination:
    namespace: memo-prd
    server: https://kubernetes.default.svc
  project: memou
  source:
    helm:
      valueFiles:
      - values.yaml
    path: backend/prd
    repoURL: https://github.com/SangYunLeee/memoBlog_cd.git
    targetRevision: HEAD
