backend:
  name: memo-backend
  replicaCount: 2
  image:
    repository: "sororiri/memo-backend"
    tag: "0.0.26"

frontend:
  name: memo-frontend
  replicaCount: 1
  image:
    repository: "sororiri/memo-front"
    tag: "0.0.25"

ingress:
  backend:
    host: memoapi.entto.shop
  frontend:
    host: memo.entto.shop
