# backend
backend:
  name: memo-backend
  replicaCount: 2
  image:
    repository: "sororiri/memo-backend"
    tag: 5
# frontend
frontend:
  name: memo-frontend
  replicaCount: 1
  image:
    repository: "sororiri/memo-frontend"
    tag: 6
# ingress
ingress:
  backend:
    host: memoapi.entto.shop
  frontend:
    host: memo.entto.shop
