# backend
backend:
  name: memo-backend
  replicaCount: 2
  image:
    repository: "sororiri/memo-backend"
    tag: 2
  env:
    - name: BACKEND_URL
      value: https://api.memou.shop
    - name: BACKEND_PORT
      value: "3001"
    - name: JWT_SECRET
      value: leesecret
    - name: HASH_ROUNDS
      value: "7"
    - name: DB_HOST
      value: "postgres.database.svc"
    - name: DB_PORT
      value: "5432"
    - name: DB_TYPE
      value: postgres
    - name: DB_USERNAME
      value: postgres
    - name: DB_PASSWORD
      value: dltkddbs12
    - name: DB_DATABASE
      value: postgres
  volumes:
    - name: host-path-volume
      hostPath:
        path: /data/nfs-w1
  volumeMounts:
    - name: host-path-volume
      mountPath: /app/public
      subPath: memo/public
# frontend
frontend:
  name: memo-frontend
  replicaCount: 1
  image:
    repository: "sororiri/memo-frontend"
    tag: 16
# ingress
ingress:
  backend:
    host: memoapi.entto.shop
  frontend:
    host: memo.entto.shop
namespace: memo
