apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-backend
spec:
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
  selector:
    app: {{ .Values.name }}-backend


---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ .Values.name }}-frontend
