apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memo-dev-backend
  namespace: argocd
spec:
  destination:
    namespace: memo-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: backend/dev
    repoURL: https://github.com/SangYunLeee/memoBlog_cd.git
    targetRevision: HEAD
