apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memou-prd-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: memou-prd
  source:
    path: _app/prd
    repoURL: https://github.com/SangYunLeee/memoBlog_cd.git
    targetRevision: HEAD
