apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: memou-dev
  namespace: argocd
spec:
  description: Memou Project
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
