apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    {{- range .Values.ingress }}
    - {{ . }}
    {{- end }}
    secretName: {{ index .Values.ingress 0 }}-tls
  rules:
  {{- range .Values.ingress }}
  - host: {{ . }}
    http:
      paths:
        - backend:
            service:
              name: {{ $.Values.name }}
              port:
                number: 80
          path: /
          pathType: Prefix
  {{- end }}
