apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  replicas: {{ .Values.backend.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        tier: backend
    spec:
      containers:
      - image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: Always
        name: {{ .Values.backend.name }}
        ports:
        - containerPort: 3001
        env:
          {{- toYaml .Values.backend.env | nindent 10 }}
        resources:
          requests:
            memory: "400Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 10
        volumeMounts:
          {{- toYaml .Values.backend.volumeMounts | nindent 10 }}
      volumes:
          {{- toYaml .Values.backend.volumes | nindent 8 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  replicas: {{ .Values.frontend.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
        tier: frontend
    spec:
      containers:
      - image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: Always
        name: {{ .Values.frontend.name }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "200m"
