apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
spec:
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
  selector:
    app: {{ .Values.backend.name }}


---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ .Values.frontend.name }}
