name: memo-backend
# backend
app:
  nodeSelector:
    kubernetes.io/hostname: node1
  replicaCount: 2
  image:
    repository: "sororiri/memo-backend"
    tag: 2
  env:
    - name: BACKEND_URL
      value: https://api-dev.memou.shop
    - name: BACKEND_PORT
      value: "3001"
    - name: JWT_SECRET
      value: leesecret
    - name: HASH_ROUNDS
      value: "7"
    - name: DB_HOST
      value: "postgres.memo-dev.svc"
    - name: DB_PORT
      value: "5432"
    - name: DB_TYPE
      value: postgres
    - name: DB_USERNAME
      value: postgres
    - name: DB_PASSWORD
      value: postgres
    - name: DB_DATABASE
      value: postgres
  volumes:
    - name: host-path-volume
      hostPath:
        path: /data/nfs-w1
  volumeMounts:
    - name: host-path-volume
      mountPath: /app/public
      subPath: memo/dev/public

# ingress
ingress:
  host: api-dev.memou.shop
